import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  renderToBuffer,
} from "@react-pdf/renderer";

export interface CertificateData {
  workspaceName: string;
  delegateName: string;
  delegateEmail: string;
  projectName: string;
  projectDescription: string | null;
  completedAt: Date;
  roiZarRands: number | null;
  awardedByName: string | null;
  className: string | null;
}

const SIGMAFY_BLUE = "#1d6dd6";
const INK = "#0e1116";
const MUTED = "#6b7280";
const BORDER = "#e5e7eb";

const styles = StyleSheet.create({
  page: {
    padding: "60 50",
    fontFamily: "Helvetica",
    fontSize: 11,
    color: INK,
    backgroundColor: "#ffffff",
  },
  border: {
    borderWidth: 6,
    borderColor: SIGMAFY_BLUE,
    borderRadius: 12,
    padding: 36,
    flexGrow: 1,
    flexDirection: "column",
  },
  brand: {
    color: SIGMAFY_BLUE,
    fontSize: 11,
    fontFamily: "Helvetica-Bold",
    letterSpacing: 3,
    textTransform: "uppercase",
    marginBottom: 6,
  },
  workspace: {
    color: MUTED,
    fontSize: 10,
    marginBottom: 30,
  },
  caption: {
    color: MUTED,
    fontSize: 12,
    fontFamily: "Helvetica-Oblique",
    marginBottom: 8,
  },
  delegateName: {
    color: INK,
    fontSize: 38,
    fontFamily: "Helvetica-Bold",
    marginBottom: 4,
    letterSpacing: 0.5,
  },
  email: {
    color: MUTED,
    fontSize: 11,
    marginBottom: 24,
  },
  bigCopy: {
    color: INK,
    fontSize: 14,
    lineHeight: 1.5,
    marginBottom: 6,
  },
  projectName: {
    color: SIGMAFY_BLUE,
    fontSize: 18,
    fontFamily: "Helvetica-Bold",
    marginTop: 6,
    marginBottom: 4,
  },
  projectDesc: {
    color: MUTED,
    fontSize: 11,
    fontFamily: "Helvetica-Oblique",
    marginBottom: 30,
  },
  metaGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 18,
    marginTop: "auto",
    paddingTop: 24,
    borderTopWidth: 1,
    borderTopColor: BORDER,
  },
  metaItem: {
    flexDirection: "column",
    minWidth: 140,
  },
  metaLabel: {
    color: MUTED,
    fontSize: 9,
    textTransform: "uppercase",
    letterSpacing: 1.2,
    marginBottom: 3,
  },
  metaValue: {
    color: INK,
    fontSize: 12,
    fontFamily: "Helvetica-Bold",
  },
  footer: {
    color: MUTED,
    fontSize: 9,
    marginTop: 18,
    fontFamily: "Helvetica-Oblique",
  },
});

const ZAR = new Intl.NumberFormat("en-ZA", {
  style: "currency",
  currency: "ZAR",
  maximumFractionDigits: 0,
});

export function CertificateDocument(props: { data: CertificateData }) {
  const d = props.data;
  const dateStr = new Intl.DateTimeFormat("en-ZA", {
    day: "numeric",
    month: "long",
    year: "numeric",
  }).format(d.completedAt);

  return (
    <Document
      title={`Sigmafy Certificate — ${d.delegateName}`}
      author={d.workspaceName}
      subject={`Certificate of Completion — ${d.projectName}`}
    >
      <Page size="A4" orientation="landscape" style={styles.page}>
        <View style={styles.border}>
          <Text style={styles.brand}>SIGMAFY · CERTIFICATE OF COMPLETION</Text>
          <Text style={styles.workspace}>Issued by {d.workspaceName}</Text>

          <Text style={styles.caption}>This certifies that</Text>
          <Text style={styles.delegateName}>{d.delegateName}</Text>
          <Text style={styles.email}>{d.delegateEmail}</Text>

          <Text style={styles.bigCopy}>has completed a Six Sigma Green Belt project,</Text>
          <Text style={styles.projectName}>{d.projectName}</Text>
          {d.projectDescription && (
            <Text style={styles.projectDesc}>{d.projectDescription}</Text>
          )}

          <View style={styles.metaGrid}>
            <View style={styles.metaItem}>
              <Text style={styles.metaLabel}>Completed</Text>
              <Text style={styles.metaValue}>{dateStr}</Text>
            </View>
            {d.roiZarRands !== null && (
              <View style={styles.metaItem}>
                <Text style={styles.metaLabel}>Estimated annual ROI</Text>
                <Text style={styles.metaValue}>{ZAR.format(d.roiZarRands)}</Text>
              </View>
            )}
            {d.className && (
              <View style={styles.metaItem}>
                <Text style={styles.metaLabel}>Cohort</Text>
                <Text style={styles.metaValue}>{d.className}</Text>
              </View>
            )}
            {d.awardedByName && (
              <View style={styles.metaItem}>
                <Text style={styles.metaLabel}>Awarded by</Text>
                <Text style={styles.metaValue}>{d.awardedByName}</Text>
              </View>
            )}
          </View>

          <Text style={styles.footer}>
            Generated by Sigmafy. Verify this certificate by signing in to the {d.workspaceName} workspace.
          </Text>
        </View>
      </Page>
    </Document>
  );
}

/** Render a CertificateData payload to a PDF Buffer. */
export async function renderCertificatePdf(data: CertificateData): Promise<Buffer> {
  return await renderToBuffer(<CertificateDocument data={data} />);
}
