import { jsonb, pgTable, uuid, text, integer, timestamp, index } from "drizzle-orm/pg-core";
import { workspaces } from "./workspaces";
import { agentThreads } from "./agent-threads";
import { statsToolRuns } from "./stats-tool-runs";

/**
 * One turn in an agent conversation. Holds both the surface text and
 * the audit-defensible receipts: every tool the assistant decided to
 * call against the Python stats engine ends up as a row in
 * `stats_tool_runs` and the message's `tool_run_ids` array references
 * those rows. That's what makes the assistant's answer defensible to
 * FDA / IATF / ISO auditors — the exact procedure + JSON input + JSON
 * output is recoverable from the message id.
 *
 * Roles:
 *   user       — the human's prompt
 *   assistant  — the model's reply
 *   tool       — a tool-call result the model received (kept so a
 *                future thread replay can be reconstructed verbatim)
 *   system     — workspace-injected guidance ahead of a turn (rare;
 *                normally the assistant's system_prompt covers this)
 *
 * `content_blocks` mirrors the Anthropic Messages-API block shape so
 * we can persist tool_use / tool_result blocks losslessly. UI renders
 * the friendlier `text` field when present; falls back to blocks.
 */
export const agentMessages = pgTable(
  "agent_messages",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    workspaceId: uuid("workspace_id")
      .notNull()
      .references(() => workspaces.id, { onDelete: "cascade" }),
    threadId: uuid("thread_id")
      .notNull()
      .references(() => agentThreads.id, { onDelete: "cascade" }),
    role: text("role", { enum: ["user", "assistant", "tool", "system"] }).notNull(),
    // Plain text for the simple text-only path. Null when the message
    // is purely tool_use / tool_result blocks.
    text: text("text"),
    // Anthropic-compatible content-block array. Persisted lossless so
    // we can re-feed it to the model on a replay.
    contentBlocks: jsonb("content_blocks"),
    // FK array (text[] in Postgres) referencing stats_tool_runs.id values
    // executed during this turn. Empty for plain text turns. Audit
    // receipts dereference these to recover the procedure call.
    toolRunIds: jsonb("tool_run_ids").notNull().default([]),
    // Token usage (input + output) for billing + per-tier rate-limit
    // accounting. Null when the message was not generated by an LLM
    // call (user messages, tool_result messages).
    inputTokens: integer("input_tokens"),
    outputTokens: integer("output_tokens"),
    // Anthropic model that produced this message (assistant role only).
    model: text("model"),
    // Stable stop reason from Anthropic: 'end_turn' | 'max_tokens' |
    // 'stop_sequence' | 'tool_use' | 'pause_turn' | 'refusal'.
    stopReason: text("stop_reason"),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => ({
    threadCreatedIdx: index("agent_messages_thread_created_idx").on(
      t.threadId,
      t.createdAt,
    ),
    workspaceCreatedIdx: index("agent_messages_workspace_created_idx").on(
      t.workspaceId,
      t.createdAt,
    ),
  }),
);

export type AgentMessage = typeof agentMessages.$inferSelect;
export type NewAgentMessage = typeof agentMessages.$inferInsert;

// Re-export so callers don't need a separate import to dereference
// receipts.
export { statsToolRuns };
