/**
 * Stats client codegen.
 *
 * Fetches the FastAPI service's OpenAPI document and writes a fully-typed
 * client to `src/generated/`. Re-run whenever the FastAPI service changes
 * its endpoints or schemas.
 *
 * Usage:
 *   STATS_API_BASE_URL=https://sigmafy-tools.fly.dev pnpm --filter @sigmafy/stats-client generate
 */
import { writeFile, mkdir } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import openapiTS, { astToString } from "openapi-typescript";

const baseUrl = process.env.STATS_API_BASE_URL ?? "https://sigmafy-tools.fly.dev";
const openapiUrl = `${baseUrl.replace(/\/$/, "")}/openapi.json`;
const outFile = resolve(process.cwd(), "src/generated/api.ts");

async function main(): Promise<void> {
  console.log(`[stats-client] fetching OpenAPI from ${openapiUrl}`);
  const ast = await openapiTS(new URL(openapiUrl));
  const code = astToString(ast);
  await mkdir(dirname(outFile), { recursive: true });
  const banner = `/**
 * AUTO-GENERATED by packages/stats-client/scripts/generate.ts
 * Source: ${openapiUrl}
 * Do not edit by hand. Re-run codegen via:
 *   pnpm --filter @sigmafy/stats-client generate
 */
`;
  await writeFile(outFile, banner + code, "utf8");
  console.log(`[stats-client] wrote ${outFile} (${code.length} bytes)`);
}

main().catch((err) => {
  console.error("[stats-client] codegen failed:", err);
  process.exit(1);
});
